local addonName, ET = ...

ET.L = ET.L or {}
local L = ET.L

-- English (Default) Localization
L["EpicTip"] = "EpicTip"
L["Options"] = "Options"
L["Enable Tooltip"] = "Enable Tooltip"
L["Show Item Level"] = "Show Item Level"
L["Show Target"] = "Show Target"
L["Show Specialization"] = "Show Specialization"
L["Anchor Tooltip to Mouse Cursor"] = "Anchor Tooltip to Mouse Cursor"
L["Hide Tooltip Health Bar"] = "Hide Tooltip Health Bar"
L["Hide NPC Health Bar"] = "Hide NPC Health Bar"
L["Hide Tooltip In Combat"] = "Hide Tooltip In Combat"
L["Show Class Icon"] = "Show Class Icon"
L["Show Role Icon"] = "Show Role Icon"
L["Show Mythic+ Rating"] = "Show Mythic+ Rating"
L["Show PvP Rating"] = "Show PvP Rating"
L["Show Mount Info"] = "Show Mount Info"
L["Show Boss Info"] = "Show Boss Info"

L["Boss Loot Highlights"] = "Boss Loot Highlights"
L["Boss Achievements"] = "Boss Achievements"
L["Show Stat Values"] = "Show Stat Values"
L["Highlight Grey Items (Ctrl)"] = "Highlight Grey Items (Ctrl)"
L["Debug Mode"] = "Debug Mode"
L["Tooltip Scale"] = "Tooltip Scale"
L["Target:"] = "Target:"
L["Health:"] = "Health:"
L["Specialization:"] = "Specialization:"
L["Role:"] = "Role:"
L["Mythic+ Rating:"] = "Mythic+ Rating:"
L["PvP Rating:"] = "PvP Rating:"
L["Item Level:"] = "Item Level:"
L["GUID:"] = "GUID:"
L["Unit ID:"] = "Unit ID:"
L["Class ID:"] = "Class ID:"
L["Spec ID:"] = "Spec ID:"
L["Inspect cooldown active"] = "Inspect cooldown active"
L["Source:"] = "Source:"
L["Type:"] = "Type:"
L["Subtype:"] = "Subtype:"
L["Slot:"] = "Slot:"
L["Stack:"] = "Stack:"
L["Vendor Price:"] = "Vendor Price:"
L["Mount Type:"] = "Mount Type:"
L["Status:"] = "Status:"
L["Faction:"] = "Faction:"

-- Configuration UI Strings
L["General"] = "General"
L["Features"] = "Features"
L["Cursor Ring"] = "Cursor Ring"
L["Appearance"] = "Appearance"
L["TrueStat"] = "TrueStat"
L["Player Info"] = "Player Info"

-- General Configuration
L["Enable EpicTip"] = "Enable EpicTip"
L["Master switch to enable or disable the addon completely"] = "Master switch to enable or disable the addon completely"
L["Overall size of tooltips (1.0 = normal size)"] = "Overall size of tooltips (1.0 = normal size)"
L["Hide all tooltips during combat"] = "Hide all tooltips during combat"
L["Choose how tooltips are positioned relative to your cursor"] = "Choose how tooltips are positioned relative to your cursor"
L["Allow addon to inspect other players for detailed information"] = "Allow addon to inspect other players for detailed information"

-- Features Configuration Keys
L["Score Only"] = "Score Only"
L["Highest Key Only"] = "Highest Key Only"
L["Score + Highest Key"] = "Score + Highest Key"
L["Detailed Stats"] = "Detailed Stats"
L["Show PvP Rating"] = "Show PvP Rating"
L["Tooltip Positioning"] = "Tooltip Positioning"
L["Enable Player Inspection"] = "Enable Player Inspection"

-- Features Configuration
L["Competitive"] = "Competitive"
L["World Content"] = "World Content"
L["Mythic+ Display Format"] = "Mythic+ Display Format"
L["Show Detailed M+ Statistics"] = "Show Detailed M+ Statistics"
L["Mount Information"] = "Mount Information"
L["Displays the player's current Mythic+ rating and seasonal progress. This is crucial for understanding a player's experience level in high-end dungeon content and helps with group formation decisions."] = "Displays the player's current Mythic+ rating and seasonal progress. This is crucial for understanding a player's experience level in high-end dungeon content and helps with group formation decisions."
L["Choose what specific Mythic+ information to display. 'Score Only' shows just the rating number, 'Highest Key' shows their best completed level, 'Both' shows rating and key level, 'Detailed' includes additional statistics."] = "Choose what specific Mythic+ information to display. 'Score Only' shows just the rating number, 'Highest Key' shows their best completed level, 'Both' shows rating and key level, 'Detailed' includes additional statistics."
L["Adds additional Mythic+ statistics such as completion ratios, timing success rates, and seasonal progress. This provides deeper insight into a player's consistency and reliability in challenging content."] = "Adds additional Mythic+ statistics such as completion ratios, timing success rates, and seasonal progress. This provides deeper insight into a player's consistency and reliability in challenging content."
L["Displays PvP ratings for Arena (2v2, 3v3, RBG) and current PvP achievements. Essential for understanding a player's PvP experience and skill level in competitive player-versus-player content."] = "Displays PvP ratings for Arena (2v2, 3v3, RBG) and current PvP achievements. Essential for understanding a player's PvP experience and skill level in competitive player-versus-player content."
L["Shows detailed mount information when hovering over mounted players, including mount name, rarity, acquisition method, and collection status. Perfect for mount collectors and those curious about rare mounts they see."] = "Shows detailed mount information when hovering over mounted players, including mount name, rarity, acquisition method, and collection status. Perfect for mount collectors and those curious about rare mounts they see."

-- Ring Configuration
L["Enable Cursor Ring"] = "Enable Cursor Ring"
L["Show a ring around your mouse cursor that changes appearance in combat"] = "Show a ring around your mouse cursor that changes appearance in combat"
L["Ring Style"] = "Ring Style"
L["Choose the visual style of the ring"] = "Choose the visual style of the ring"
L["Visibility Mode"] = "Visibility Mode"
L["Choose when the ring should be visible"] = "Choose when the ring should be visible"
L["Ring Size"] = "Ring Size"
L["Size of the cursor ring"] = "Size of the cursor ring"
L["Ring Opacity"] = "Ring Opacity"
L["Transparency of the ring (0 = invisible, 1 = fully visible)"] = "Transparency of the ring (0 = invisible, 1 = fully visible)"
L["Cursor Glow Effects"] = "Cursor Glow Effects"
L["Enable Cursor Glow"] = "Enable Cursor Glow"
L["Enable glowing effects that follow your cursor"] = "Enable glowing effects that follow your cursor"
L["Glow Texture"] = "Glow Texture"
L["Choose the texture for the cursor glow effect"] = "Choose the texture for the cursor glow effect"
L["Use Class Color"] = "Use Class Color"
L["Use your character's class color for the glow"] = "Use your character's class color for the glow"
L["Custom Glow Color"] = "Custom Glow Color"
L["Choose a custom color for the glow effect"] = "Choose a custom color for the glow effect"
L["Glow Size"] = "Glow Size"
L["Size of the cursor glow effect"] = "Size of the cursor glow effect"
L["Glow Opacity"] = "Glow Opacity"
L["Transparency of the glow effect (0 = invisible, 1 = fully visible)"] = "Transparency of the glow effect (0 = invisible, 1 = fully visible)"
L["Tail Effects"] = "Tail Effects"
L["Enable Tail Effect"] = "Enable Tail Effect"
L["Show a trailing effect behind the cursor"] = "Show a trailing effect behind the cursor"
L["Tail Length"] = "Tail Length"
L["Number of tail segments"] = "Number of tail segments"
L["Tail Effect Style"] = "Tail Effect Style"
L["Choose the animation style for the tail"] = "Choose the animation style for the tail"
L["Pulse Effects"] = "Pulse Effects"
L["Enable Pulse Effect"] = "Enable Pulse Effect"
L["Add a pulsing animation when the cursor is stationary"] = "Add a pulsing animation when the cursor is stationary"
L["Pulse Speed"] = "Pulse Speed"
L["Speed of the pulsing animation"] = "Speed of the pulsing animation"
L["Click Effects"] = "Click Effects"
L["Enable Click Glow"] = "Enable Click Glow"
L["Show an explosion effect when you click"] = "Show an explosion effect when you click"
L["Click Effect Size"] = "Click Effect Size"
L["Size of the click explosion effect"] = "Size of the click explosion effect"
L["Combat Settings"] = "Combat Settings"
L["Combat Only"] = "Combat Only"
L["Only show glow effects during combat"] = "Only show glow effects during combat"
L["Hide in Combat"] = "Hide in Combat"
L["Hide glow effects during combat"] = "Hide glow effects during combat"

-- Appearance Configuration
L["Background"] = "Background"
L["Background Settings"] = "Background Settings"
L["Background Color"] = "Background Color"
L["Color of the tooltip background"] = "Color of the tooltip background"
L["Background Fade"] = "Background Fade"
L["Apply a fade effect to the tooltip background"] = "Apply a fade effect to the tooltip background"
L["Reaction-Based Background"] = "Reaction-Based Background"
L["Color the background based on unit reaction (hostile = red, friendly = green, etc.)"] = "Color the background based on unit reaction (hostile = red, friendly = green, etc.)"
L["Class-Colored Background"] = "Class-Colored Background"
L["Color the background based on the player's class color"] = "Color the background based on the player's class color"
L["Border"] = "Border"
L["Border Settings"] = "Border Settings"
L["Border Color"] = "Border Color"
L["Color of the tooltip border"] = "Color of the tooltip border"
L["Border Width"] = "Border Width"
L["Width of the tooltip border in pixels"] = "Width of the tooltip border in pixels"
L["Class-Colored Border"] = "Class-Colored Border"
L["Color the border based on the player's class color"] = "Color the border based on the player's class color"
L["Text Filtering"] = "Text Filtering"
L["Text Filtering Options"] = "Text Filtering Options"
L["Hide Specialization/Class Text"] = "Hide Specialization/Class Text"
L["Remove specialization and class text lines (e.g., 'Shadow Priest')"] = "Remove specialization and class text lines (e.g., 'Shadow Priest')"
L["Hide PvP Text"] = "Hide PvP Text"
L["Remove 'PvP Enabled' text from tooltips"] = "Remove 'PvP Enabled' text from tooltips"
L["Hide Right-Click Text"] = "Hide Right-Click Text"
L["Remove 'Right click for more options' text from tooltips"] = "Remove 'Right click for more options' text from tooltips"
L["Font Configuration"] = "Font Configuration"
L["Font Family"] = "Font Family"
L["Choose the font family for tooltip text"] = "Choose the font family for tooltip text"
L["Font Preview"] = "Font Preview"
L["Title Font Size"] = "Title Font Size"
L["Font size for tooltip titles and headers"] = "Font size for tooltip titles and headers"
L["Info Font Size"] = "Info Font Size"
L["Font size for general tooltip information"] = "Font size for general tooltip information"
L["Header Font Size"] = "Header Font Size"
L["Font size for section headers in tooltips"] = "Font size for section headers in tooltips"
L["Description Font Size"] = "Description Font Size"
L["Font size for descriptions and secondary text"] = "Font size for descriptions and secondary text"
L["Reset Font Sizes"] = "Reset Font Sizes"
L["Reset all font sizes to their default values"] = "Reset all font sizes to their default values"

-- TrueStat Configuration
L["Enhanced Item Analysis and True Stat Values"] = "Enhanced Item Analysis and True Stat Values"
L["Item Information"] = "Item Information"
L["Enhanced Item Details and Analysis"] = "Enhanced Item Details and Analysis"
L["Enhanced Item Information"] = "Enhanced Item Information"
L["Adds comprehensive item details including vendor prices, drop sources, item comparisons, and upgrade paths. This feature significantly improves item tooltips with valuable context for equipment decisions."] = "Adds comprehensive item details including vendor prices, drop sources, item comparisons, and upgrade paths. This feature significantly improves item tooltips with valuable context for equipment decisions."
L["Show Detailed Item Analysis"] = "Show Detailed Item Analysis"
L["Includes additional item analysis such as stat efficiency, upgrade potential, socket information, and set piece compatibility. Provides deeper insight into item value and optimization opportunities."] = "Includes additional item analysis such as stat efficiency, upgrade potential, socket information, and set piece compatibility. Provides deeper insight into item value and optimization opportunities."
L["Show Item Source Information"] = "Show Item Source Information"
L["Displays where items can be obtained including dungeon drops, vendor purchases, quest rewards, and crafting recipes. Essential for planning acquisition strategies."] = "Displays where items can be obtained including dungeon drops, vendor purchases, quest rewards, and crafting recipes. Essential for planning acquisition strategies."
L["Show Item Value Analysis"] = "Show Item Value Analysis"
L["Displays vendor sell prices, estimated auction house values, and relative item worth. Helps with inventory management and financial decisions."] = "Displays vendor sell prices, estimated auction house values, and relative item worth. Helps with inventory management and financial decisions."
L["True Stat Values"] = "True Stat Values"
L["Accurate Stat Calculations and Analysis"] = "Accurate Stat Calculations and Analysis"
L["Shows accurate stat values including diminishing returns calculations, effective percentages, and real impact on character performance. Particularly useful for understanding how stats actually affect your character beyond the basic tooltip numbers."] = "Shows accurate stat values including diminishing returns calculations, effective percentages, and real impact on character performance. Particularly useful for understanding how stats actually affect your character beyond the basic tooltip numbers."
L["Diminishing Returns Analysis"] = "Diminishing Returns Analysis"
L["Displays how stat effectiveness decreases at higher values due to diminishing returns. Shows both current effectiveness and optimal stat distribution recommendations."] = "Displays how stat effectiveness decreases at higher values due to diminishing returns. Shows both current effectiveness and optimal stat distribution recommendations."
L["Stat Comparison Analysis"] = "Stat Comparison Analysis"
L["Compares current item stats with equipped gear, showing upgrade potential and stat changes. Includes percentage improvements and optimization suggestions."] = "Compares current item stats with equipped gear, showing upgrade potential and stat changes. Includes percentage improvements and optimization suggestions."
L["Stat Weight Calculations"] = "Stat Weight Calculations"
L["Displays stat weights and relative values for your current spec, helping prioritize stats for maximum performance improvement. Based on simulation data and community research."] = "Displays stat weights and relative values for your current spec, helping prioritize stats for maximum performance improvement. Based on simulation data and community research."
L["Stat Display Precision"] = "Stat Display Precision"
L["Number of decimal places to show for stat calculations"] = "Number of decimal places to show for stat calculations"
L["Advanced Options"] = "Advanced Options"
L["Advanced Item and Stat Configuration"] = "Advanced Item and Stat Configuration"
L["Use Simulation Data"] = "Use Simulation Data"
L["Incorporate simulation data from popular theorycrafting tools for more accurate stat weights and recommendations. May require periodic updates."] = "Incorporate simulation data from popular theorycrafting tools for more accurate stat weights and recommendations. May require periodic updates."
L["Item Level Analysis Threshold"] = "Item Level Analysis Threshold"
L["Only show detailed analysis for items above this item level to reduce tooltip clutter on low-level gear"] = "Only show detailed analysis for items above this item level to reduce tooltip clutter on low-level gear"
L["Cache Stat Calculations"] = "Cache Stat Calculations"
L["Cache complex stat calculations to improve performance. Recommended for high-end systems. Disable if experiencing memory issues."] = "Cache complex stat calculations to improve performance. Recommended for high-end systems. Disable if experiencing memory issues."
L["Show Developer Information"] = "Show Developer Information"

-- General Configuration Keys
L["Master switch to enable or disable the addon completely"] = "Master switch to enable or disable the addon completely"
L["Tooltip Scale"] = "Tooltip Scale"
L["Hide Tooltips In Combat"] = "Hide Tooltips In Combat"
L["Hide all tooltips during combat"] = "Hide all tooltips during combat"
L["Tooltip Positioning"] = "Tooltip Positioning"
L["Choose how tooltips are positioned relative to your cursor"] = "Choose how tooltips are positioned relative to your cursor"
L["Default (WoW Default)"] = "Default (WoW Default)"
L["Follow Mouse Cursor"] = "Follow Mouse Cursor"
L["Smart Positioning"] = "Smart Positioning"
L["Enable Player Inspection"] = "Enable Player Inspection"
L["Allow addon to inspect other players for detailed information"] = "Allow addon to inspect other players for detailed information"
L["Display technical item and stat information useful for addon development and debugging. Not recommended for normal use."] = "Display technical item and stat information useful for addon development and debugging. Not recommended for normal use."

-- Player Info Configuration
L["Player Information Display"] = "Player Information Display"
L["Enhanced Player Details and Statistics"] = "Enhanced Player Details and Statistics"
L["Displays comprehensive player information including achievements, progression, guild details, and character statistics. Provides valuable context when inspecting other players or reviewing your own progress."] = "Displays comprehensive player information including achievements, progression, guild details, and character statistics. Provides valuable context when inspecting other players or reviewing your own progress."
L["Show Player Achievements"] = "Show Player Achievements"
L["Display notable achievements, completion percentages, and achievement points. Helps assess player experience and dedication."] = "Display notable achievements, completion percentages, and achievement points. Helps assess player experience and dedication."
L["Show Guild Information"] = "Show Guild Information"
L["Display guild name, rank, and guild achievements. Useful for understanding player affiliations and guild progression."] = "Display guild name, rank, and guild achievements. Useful for understanding player affiliations and guild progression."
L["Show Character Statistics"] = "Show Character Statistics"
L["Display detailed character stats including played time, honor kills, and various gameplay metrics."] = "Display detailed character stats including played time, honor kills, and various gameplay metrics."
L["Show Progression Information"] = "Show Progression Information"
L["Display raid and dungeon progression, including completion status and difficulty levels achieved."] = "Display raid and dungeon progression, including completion status and difficulty levels achieved."
L["Player Info Display Options"] = "Player Info Display Options"
L["Customize Player Information Display"] = "Customize Player Information Display"
L["Compact Display Mode"] = "Compact Display Mode"
L["Show player information in a more compact format to reduce tooltip size while maintaining essential details."] = "Show player information in a more compact format to reduce tooltip size while maintaining essential details."
L["Show Only Recent Achievements"] = "Show Only Recent Achievements"
L["Limit achievement display to recent accomplishments to keep tooltips focused and relevant."] = "Limit achievement display to recent accomplishments to keep tooltips focused and relevant."
L["Include Cross-Realm Information"] = "Include Cross-Realm Information"
L["Display server and cross-realm information for players from different realms."] = "Display server and cross-realm information for players from different realms."

-- Debug and Status Messages
L["Loading"] = "Loading"
L["Loaded"] = "Loaded"
L["Enabled"] = "Enabled"
L["Disabled"] = "Disabled"
L["Initializing"] = "Initializing"
L["Ready"] = "Ready"

-- PlayerInfo Configuration Keys
L["Show Item Level"] = "Show Item Level"
L["Show Class Icons"] = "Show Class Icons"
L["Show Role Icons"] = "Show Role Icons"
L["Show Guild Rank"] = "Show Guild Rank"
L["Show Current Target"] = "Show Current Target"
L["Hide Player Health Bars"] = "Hide Player Health Bars"
L["Hide NPC Health Bars"] = "Hide NPC Health Bars"
L["Show Health Numbers"] = "Show Health Numbers"

-- TrueStat Configuration Keys
L["Enhanced Item Information"] = "Enhanced Item Information"
L["Show Detailed Item Analysis"] = "Show Detailed Item Analysis"
L["Show Item Source Information"] = "Show Item Source Information"
L["Show Item Value Analysis"] = "Show Item Value Analysis"
L["Diminishing Returns Analysis"] = "Diminishing Returns Analysis"
L["Stat Comparison Analysis"] = "Stat Comparison Analysis"
L["Stat Weight Calculations"] = "Stat Weight Calculations"
L["Stat Display Precision"] = "Stat Display Precision"
L["Number of decimal places to show for stat calculations"] = "Number of decimal places to show for stat calculations"
L["Use Simulation Data"] = "Use Simulation Data"
L["Item Level Analysis Threshold"] = "Item Level Analysis Threshold"
L["Cache Stat Calculations"] = "Cache Stat Calculations"
L["Show Developer Information"] = "Show Developer Information"
L["Error"] = "Error"
L["Warning"] = "Warning"
L["Debug"] = "Debug"
L["Cache cleared"] = "Cache cleared"
L["Cache updated"] = "Cache updated"
L["Data refreshed"] = "Data refreshed"
L["Configuration saved"] = "Configuration saved"
L["Configuration loaded"] = "Configuration loaded"
L["Module loaded"] = "Module loaded"
L["Module disabled"] = "Module disabled"
L["Performance warning"] = "Performance warning"
L["Memory usage high"] = "Memory usage high"
L["Update available"] = "Update available"
L["Compatibility check"] = "Compatibility check"
L["API deprecated"] = "API deprecated"
L["Classification:"] = "Classification:"
L["Level:"] = "Level:"
L["Reaction:"] = "Reaction:"
